/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.junit.jupiter.api.Test;
import org.example.Item;
import org.example.SILab2;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
public class SILab2Test {

    @Test
    void everyStatementTest() {
        //Т1 Null list фрла исклучок
        assertThrows(RuntimeException.class, () -> SILab2.checkCart(null, "1234567890123456"));

        //Т2 Item со null име фрла исклучок
        Item nullName = new Item(null, 1, 100, 0);
        assertThrows(RuntimeException.class, () -> SILab2.checkCart(List.of(nullName), "1234567890123456"));

        //Т3 валиден Item со сите услови исполнети,попуст и -30
        Item item = new Item("TV", 12, 400, 0.2);
        double expected = 400 * 0.8 * 12 - 30;
        assertEquals(expected, SILab2.checkCart(List.of(item), "1234567890123456"), 0.001);

        //Т4 невалиден број на картичка(букви)
        Item valid = new Item("Mouse", 1, 100, 0);
        assertThrows(RuntimeException.class, () -> SILab2.checkCart(List.of(valid), "1234abcd5678efgh"));

        //Т5 невалиден број на картичка(<16 цифри)
        assertThrows(RuntimeException.class, () -> SILab2.checkCart(List.of(valid), "12345678"));
    }

    @Test
    void MultipleCondition() {
        //T1 TXX-само условот за цена(> 300) е исполнет
        //-30 поени
        Item i1 = new Item("Laptop", 2, 500, 0);
        double expected1 = 500 * 2 - 30;
        assertEquals(expected1, SILab2.checkCart(List.of(i1), "5555666677778888"), 0.001);
        System.out.println("TXX test successful");

        //Т2 FTX-само условот за попуст(> 0) е исполнет
        //пресметка со попуст и -30 поени
        Item i2 = new Item("Mouse", 4, 200, 0.2);
        double expected2 = 200 * 0.8 * 4 - 30;
        assertEquals(expected2, SILab2.checkCart(List.of(i2), "9999000011112222"), 0.001);
        System.out.println("FTX test successful");

        //Т3 FFT-само условот за количина(> 10) е исполнет
        //нормална пресметка без попуст ама со -30 поени
        Item i3 = new Item("Cable", 11, 50, 0);
        double expected3 = 50 * 11 - 30;
        assertEquals(expected3, SILab2.checkCart(List.of(i3), "3333444455556666"), 0.001);
        System.out.println("FFT test successful");

        //Т4 FFF-ниту еден услов не е исполнет
        //нормална пресметка без попуст и без одземање
        Item i4 = new Item("Pen", 1, 100, 0);
        double expected4 = 100 * 1;
        assertEquals(expected4, SILab2.checkCart(List.of(i4), "2222333344445555"), 0.001);
        System.out.println("FFF test successful");
    }
}